-- Test account scaffold for Example forecasting modernization
-- Creates empty database, schema, and core tables expected by the project.
-- Safe to run multiple times; IF NOT EXISTS guards prevent overwriting existing objects.

-- Database and schema
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_EXAMPLE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING;

-- Forecast input table (global region)
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_INPUT_GLOBAL (
    REGION STRING,
    ISRC STRING,
    DISPLAY_ARTIST STRING,
    TRACK STRING,
    RELEASE_DATE DATE,
    WEEK_ENDING DATE,
    STREAMS NUMBER(38,0)
);

-- Forecast output tables (populated by stored procedures / ML function)
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_OUTPUT_GLOBAL (
    REGION STRING,
    ISRC STRING,
    DISPLAY_ARTIST STRING,
    TRACK STRING,
    RELEASE_DATE DATE,
    WEEK_ENDING DATE,
    STREAMS_ACTUAL NUMBER(38,0),
    STREAMS_PREDICTED NUMBER(38,0),
    IS_FORECAST NUMBER(1,0),
    MODEL_FILE STRING
);

CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_OUTPUT_GLOBAL_ML (
    TIMESTAMP TIMESTAMP_NTZ,
    TARGET_VALUE NUMBER,
    TARGET_NAME STRING,
    FORECASTED_VALUE NUMBER,
    LOWER_BOUND NUMBER,
    UPPER_BOUND NUMBER,
    HORIZON NUMBER,
    METRIC STRING
);

-- Optional helper table for cost parameters (used by setup scripts)
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING.SFE_COST_PARAMS (
    PARAM_NAME STRING,
    PARAM_VALUE FLOAT,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
