-- Snowflake setup script for Example Forecasting modernization
-- Creates database, schema, Snowpark-optimized warehouse, model stage, cost parameter table, and estimator functions.
-- Run inside Snowflake with appropriate privileges (ACCOUNTADMIN or delegated role).

-- 1. Database and schema
CREATE DATABASE IF NOT EXISTS SNOWFLAKE_EXAMPLE;
CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING;

-- 2. Snowpark-optimized warehouse (use RESOURCE MONITORS as needed)
CREATE WAREHOUSE IF NOT EXISTS SFE_SP_WH
    WAREHOUSE_SIZE = 'medium'
    WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- 3. Model stage for artifacts
CREATE STAGE IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING.SFE_MODEL_STAGE;

-- 4. Cost parameter table (editable values)
CREATE TABLE IF NOT EXISTS SNOWFLAKE_EXAMPLE.FORECASTING.SFE_COST_PARAMS (
    PARAM_NAME STRING,
    PARAM_VALUE FLOAT,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Example seed values (update with contract specifics)
MERGE INTO SNOWFLAKE_EXAMPLE.FORECASTING.SFE_COST_PARAMS t
USING (
    SELECT 'DOLLARS_PER_CREDIT' AS PARAM_NAME, 3.00 AS PARAM_VALUE UNION ALL
    SELECT 'SP_WH_MEDIUM_CREDITS_PER_HOUR', 6.00
) s
ON t.PARAM_NAME = s.PARAM_NAME
WHEN MATCHED THEN UPDATE SET PARAM_VALUE = s.PARAM_VALUE, UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (PARAM_NAME, PARAM_VALUE) VALUES (s.PARAM_NAME, s.PARAM_VALUE);

-- 5. Estimator functions
CREATE OR REPLACE FUNCTION SNOWFLAKE_EXAMPLE.FORECASTING.SFE_ESTIMATE_WH_COST(
    RUNTIME_HOURS FLOAT,
    CREDITS_PER_HOUR FLOAT,
    DOLLARS_PER_CREDIT FLOAT
)
RETURNS OBJECT
AS
$$
  SELECT OBJECT_CONSTRUCT(
      'estimated_credits', RUNTIME_HOURS * CREDITS_PER_HOUR,
      'estimated_dollars', RUNTIME_HOURS * CREDITS_PER_HOUR * DOLLARS_PER_CREDIT
  )
$$;

-- 6. Verification queries (commented; run manually when needed)
-- SELECT SNOWFLAKE_EXAMPLE.FORECASTING.SFE_ESTIMATE_WH_COST(2, (SELECT PARAM_VALUE FROM SNOWFLAKE_EXAMPLE.FORECASTING.SFE_COST_PARAMS WHERE PARAM_NAME='SP_WH_LARGE_CREDITS_PER_HOUR'), (SELECT PARAM_VALUE FROM SNOWFLAKE_EXAMPLE.FORECASTING.SFE_COST_PARAMS WHERE PARAM_NAME='DOLLARS_PER_CREDIT'));
