-- SNOWFLAKE.ML.FORECAST path for Example forecasting modernization
-- Docs: https://docs.snowflake.com/en/user-guide/ml-functions/forecasting

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST SNOWFLAKE_EXAMPLE.FORECASTING.SFE_GLOBAL_FORECAST_MODEL(
    INPUT_DATA => TABLE(
        SELECT
            WEEK_ENDING,
            STREAMS
        FROM SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_INPUT_GLOBAL
        WHERE REGION = 'Global'
    ),
    TIMESTAMP_COLNAME => 'WEEK_ENDING',
    TARGET_COLNAME => 'STREAMS'
);

-- Example inference
SELECT *
FROM TABLE(
  SNOWFLAKE_EXAMPLE.FORECASTING.SFE_GLOBAL_FORECAST_MODEL!FORECAST(
    FORECASTING_PERIODS => 12
  )
);

-- Persist results to output table
CREATE OR REPLACE TABLE SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_OUTPUT_GLOBAL_ML AS
SELECT *
FROM TABLE(
  SNOWFLAKE_EXAMPLE.FORECASTING.SFE_GLOBAL_FORECAST_MODEL!FORECAST(
    FORECASTING_PERIODS => 12
  )
);

-- Validate the output
SELECT * FROM SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_OUTPUT_GLOBAL_ML LIMIT 10;

-- Optional: To schedule the forecast to run daily, uncomment the following section.
/*
-- Optional task to refresh forecasts daily using ML function
CREATE OR REPLACE TASK SNOWFLAKE_EXAMPLE.FORECASTING.SFE_TASK_FORECAST_ML
  WAREHOUSE = SFE_SP_WH
  SCHEDULE = 'USING CRON 0 4 * * * America/Los_Angeles'
AS
  CREATE OR REPLACE TABLE SNOWFLAKE_EXAMPLE.FORECASTING.FORECAST_OUTPUT_GLOBAL_ML AS
  SELECT *
  FROM TABLE(
    SNOWFLAKE_EXAMPLE.FORECASTING.SFE_GLOBAL_FORECAST_MODEL!FORECAST(
      FORECASTING_PERIODS => 12
    )
  );

ALTER TASK SNOWFLAKE_EXAMPLE.FORECASTING.SFE_TASK_FORECAST_ML RESUME;
*/
